sonar.projectKey=portfolio-api
sonar.host.url=http://192.168.0.15:30900
sonar.sources=services/portfolio-api
sonar.tests=services/portfolio-api
sonar.test.inclusions=services/portfolio-api/**/*.test.js
sonar.exclusions=**/node_modules/**
